name: Pull image from Docker Hub and deploy it to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
          echo "${{ secrets.AWS_SSHKEY }}" > id_rsa
          chmod 600 id_rsa 

      - name: Create deployment script
        run: |
          cat << 'EOF' > ec2.sh
          #!/bin/bash
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          sudo docker pull $DOCKER_IMAGE_URL
          sudo docker stop be-clinicmate || true
          sudo docker rm be-clinicmate || true
          sudo docker run -d --name be-clinicmate -p $EC2_BE_PORT:$EC2_BE_PORT $DOCKER_IMAGE_URL
          EOF

          chmod +x ec2.sh

      - name: Copy deployment script to AWS EC2
        run: |
          scp -i id_rsa ec2.sh ubuntu@${{ secrets.EC2_BE_IP }}:~

      - name: Execute deployment script on AWS EC2
        run: |
          ssh -i id_rsa ubuntu@${{ secrets.EC2_BE_IP }} "DOCKER_IMAGE_URL=${{ vars.DOCKER_IMAGE_URL }} EC2_BE_PORT=${{ secrets.EC2_BE_PORT }} bash -s" < ec2.sh
