name: Pull image from Docker Hub and deploy it to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.AWS_SSHKEY }}" > id_rsa
          chmod 600 id_rsa 

      - name: SSH into EC2 and deploy
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no ubuntu@13.213.74.144 << 'EOF'
          
          # Update system and install Docker
          sudo apt update
          sudo apt install -y docker.io

          # Ensure Docker service is running
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          # Create and execute deployment script
          cat << 'SCRIPT' > ~/ec2.sh
          #!/bin/bash
          
          # Pull latest image from Docker Hub
          sudo docker pull putrawan/be-clinicmate:latest

          # Stop and remove existing container
          sudo docker stop be-clinicmate || true
          sudo docker rm be-clinicmate || true

          # Run new container
          sudo docker run -d --name be-clinicmate -p 3000:3000 putrawan/be-clinicmate:latest
          SCRIPT

          chmod +x ~/ec2.sh
          bash ~/ec2.sh
          EOF
